# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menubdfgd = QtWidgets.QMenu(parent=self.menubar)
        self.menubdfgd.setObjectName("menubdfgd")
        self.menusdgs = QtWidgets.QMenu(parent=self.menubar)
        self.menusdgs.setObjectName("menusdgs")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionfgsg = QtGui.QAction(parent=MainWindow)
        self.actionfgsg.setObjectName("actionfgsg")
        self.menubdfgd.addAction(self.actionfgsg)
        self.menubar.addAction(self.menubdfgd.menuAction())
        self.menubar.addAction(self.menusdgs.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RAGE"))
        self.menubdfgd.setTitle(_translate("MainWindow", "bdfgd"))
        self.menusdgs.setTitle(_translate("MainWindow", "sdgs"))
        self.actionfgsg.setText(_translate("MainWindow", "fgsg"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
